### PR TITLE
Fixed and updated README.md

### PR DESCRIPTION
**Pull request by larsschellhas**
I saw some broken links to the examples and fixed them for you. 
At the same time I changed other links to use HTTPS instead of HTTP, if possible. 
And analog to the first paper, I´ve added a link to the manuscript of the second paper.
Last but not least, I´ve updated the Copyright year to 2019.

### CODE REVIEW

**Comment by l-kotzur** [comment]
Hey Lars,

thanks for your input. I had it already fixed in the latest version.

Best
Leander

**Comment by larsschellhas** [comment]
Hey Leander,
alright! I forgot to look into the development branch 🤦🏼‍♂️
Best
Lars

**Comment by l-kotzur** [comment]
Ah, sorry I saw that you also updated additionally the local links to the examples. If you want, you can reopen it ;)

**Comment by larsschellhas** [comment]
Thanks, but I´ve just deleted my fork 😅 and it seems like I cannot open the pull request again now :/

**Comment by l-kotzur** [comment]
Ok. I was too rush either. Anyway, thanks for the contributions. I would have liked to include it.

**Comment by larsschellhas** [comment]
I would have loved for it to be included. Give me a minute :D

**Pull request closed without merging**
