### PR TITLE
Fix depreciation

### PR DESCRIPTION
**Pull request by l-kotzur**
@jo-omoyele @julian-belina 

Heyho, it was a small fix and the depreciation warnings should no longer appear. Could you please approve it? I will publish it on PyPI.

Greetings to the world's best energy systems analysis department :P

### CODE REVIEW

**Comment by l-kotzur** [comment]
A damn. It see the challenge.

**Comment by julian-belina** [comment]
@l-kotzur you can also adjust the testpipeline. Not each version of tsam has to be compatible with all dependency versions. This just hast to be reflected in the dependency constraints.

**Comment by l-kotzur** [comment]
Hey, I just took back the fixing of @jo-omoyele ignoring the warning, since the tests worked with future_stack=True. Therefore, future pandas version wont destroy the code.

**Comment by l-kotzur** [comment]
@julian-belina I preferred your approach and modified also the required python version for PyPI.

**Comment by l-kotzur** [comment]
@julian-belina Can you approve?

**Comment by julian-belina** [comment]
@l-kotzur I, will approve the merge once all tests suceeded. Do you need the new version asap?

**Comment by l-kotzur** [comment]
Appreciated! Take your time.

**Comment by julian-belina** [comment]
@l-kotzur, if you got some spare time could you delete some of the stale branches on this repository? Some of them are very old but I dont want to delte anything that might be used by someone.

**Comment by julian-belina** [comment]
@l-kotzur, also i increased the lower numpy limit by quite a bit based on the python compatability that is posted here:
https://endoflife.date/numpy

**Comment by l-kotzur** [comment]
> @l-kotzur, if you got some spare time could you delete some of the stale branches on this repository? Some of them are very old but I dont want to delte anything that might be used by someone.

I did! Thanks for pointing out.

**Review by julian-belina — APPROVED** [review]
Looks good to me

**Comment by julian-belina** [comment]
@l-kotzur any last thoughts? Otherwise I think its ready to merge. Do you create the release and publish to pypi?

Greetings to the best of offspring of the institute :)

**Comment by l-kotzur** [comment]
Thanks a lot for pushing this topic and also maintaining the packages! I will make the releases. It was already due since some month.

**Pull request merged**
