### PR TITLE
Limit pandas

### PR DESCRIPTION
**Pull request by jo-omoyele**
Limit pandas and Numpy. File deprecation warnings

### CODE REVIEW

**Review by julian-belina — APPROVED** [review]
Looks good to me

**Comment by l-kotzur** [comment]
Heyho @jo-omoyele @julian-belina 

Thanks for contributing!

Could you shortly explain why you did this? This limits the usage for. Is it just about the depreciation warning or is it already failing? If the first, it would be better to fix the code instead of limiting the version. If you do the latter, you will destroy the integration of the whole user base using newer versions of pandas or Python. 

Please give a short hint before releasing on PyPI. I can also take a look.

**Comment by julian-belina** [comment]
Hey @l-kotzur, we did some testing and the tests are already failing for the exlcuded versions. We are planning to update the code so its compatible with the new versions of its dependencies. Unfortunately I cant give a timeline yet.

**Comment by l-kotzur** [comment]
Ok. Perhaps I will find some time later this day and can take a look. There is an issue for this #81 and a pull request #82 doing parts of this fix.

**Comment by jo-omoyele** [comment]
Hello @l-kotzur, we are aware of these issues. It might take a couple of weeks to fix properly based on our schedules. However, we needed a quick approach to filter the warnings while we take our time fixing the issues.

**Comment by julian-belina** [comment]
@l-kotzur, thank you any help is appreciated.

**Pull request merged**
