### PR TITLE
Update installation, fix some warning move to src layout

### PR DESCRIPTION
**Pull request by julian-belina**
- I have transitioned from setup.py to pyproject.toml . https://github.com/FZJ-IEK3-VSA/tsam/issues/89
- Changed the layout from flat to source. [See here for advantages](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/)
- Updated the installation description in the README.md
- Fixed a couple of deprecation and future warnings, reported in https://github.com/FZJ-IEK3-VSA/tsam/issues/91

### CODE REVIEW

**Comment by l-kotzur** [comment]
@julian-belina can you add yourself as maintainer?

**Review by l-kotzur — APPROVED** [review]
Thanks for the update. The import and integration seem to stay the same as before... Therefore, approved!

**Comment by julian-belina** [comment]
> @julian-belina can you add yourself as maintainer?

I have added myself as a maintainer and will merge as soon as the testing is done.

**Comment by julian-belina** [comment]
- I have transitioned from setup.py to pyproject.toml . https://github.com/FZJ-IEK3-VSA/tsam/issues/89
- Changed the layout from flat to source. [See here for advantages](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/)
- Updated the installation description in the README.md
- Fixed a couple of deprecation and future warnings, reported in https://github.com/FZJ-IEK3-VSA/tsam/issues/91

**Pull request merged**
